export const states = {
    Acre:  'Acre', 
    Alagoas:  'Alagoas', 
    Amapa:  'Amapa', 
    Amazonas:  'Amazonas', 
    Bahia:  'Bahia', 
    Ceara:  'Ceara', 
    DistritoFederal:  'DistritoFederal', 
    EspiritoSanto:  'EspiritoSanto', 
    Goias:  'Goias', 
    Maranhao:  'Maranhao', 
    MatoGrosso:  'MatoGrosso', 
    MatoGrossoDoSul:  'MatoGrossoDoSul', 
    MinasGerais:  'MinasGerais', 
    Para:  'Para', 
    Paraiba:  'Paraiba', 
    Parana:  'Parana', 
    Pernambuco:  'Pernambuco', 
    Piaui:  'Piaui', 
    RioDeJaneiro:  'RioDeJaneiro', 
    RioGrandeDoNorte:  'RioGrandeDoNorte', 
    RioGrandeDoSul:  'RioGrandeDoSul', 
    Rondonia:  'Rondonia', 
    Roraima:  'Roraima', 
    SantaCatarina:  'SantaCatarina', 
    SaoPaulo:  'SaoPaulo', 
    Sergipe:  'Sergipe', 
    Tocantins: 'Tocantins'
}

export const metadata = {
    Acre: { title: 'Acre', code: 'AC', flag: require('../resources/flags/acre.png') },
    Alagoas: { title: 'Alagoas', code: 'AL', flag: require('../resources/flags/alagoas.png') },
    Amapa: { title: 'Amapá', code: 'AP', flag: require('../resources/flags/amapa.png') },
    Amazonas: { title: 'Amazonas', code: 'AM', flag: require('../resources/flags/amazonas.png') },
    Bahia: { title: 'Bahia', code: 'BA', flag: require('../resources/flags/bahia.png') },
    Ceara: { title: 'Ceará', code: 'CE', flag: require('../resources/flags/ceara.png') },
    DistritoFederal: { title: 'Distrito Federal', code: 'DF', flag: require('../resources/flags/distrito-federal.png') },
    EspiritoSanto: { title: 'Espírito Santo', code: 'ES', flag: require('../resources/flags/espirito-santo.png') },
    Goias: { title: 'Goiás', code: 'GO', flag: require('../resources/flags/goias.png') },
    Maranhao: { title: 'Maranhão', code: 'MA', flag: require('../resources/flags/maranhao.png') },
    MatoGrosso: { title: 'Mato Grosso', code: 'MT', flag: require('../resources/flags/mato-grosso.png') },
    MatoGrossoDoSul: { title: 'Mato Grosso do Sul', code: 'MS', flag: require('../resources/flags/mato-grosso-do-sul.png') },
    MinasGerais: { title: 'Minas Gerais', code: 'MG', flag: require('../resources/flags/minas-gerais.png') },
    Para: { title: 'Pará', code: 'PA', flag: require('../resources/flags/para.png') },
    Paraiba: { title: 'Paraíba', code: 'PB', flag: require('../resources/flags/paraiba.png') },
    Parana: { title: 'Paraná', code: 'PR', flag: require('../resources/flags/parana.png') },
    Pernambuco: { title: 'Pernambuco', code: 'PE', flag: require('../resources/flags/pernambuco.png') },
    Piaui: { title: 'Piauí', code: 'PI', flag: require('../resources/flags/piaui.png') },
    RioDeJaneiro: { title: 'Rio de Janeiro', code: 'RJ', flag: require('../resources/flags/rio-de-janeiro.png') },
    RioGrandeDoNorte: { title: 'Rio Grande do Norte', code: 'RN', flag: require('../resources/flags/rio-grande-do-norte.png') },
    RioGrandeDoSul: { title: 'Rio Grande do Sul', code: 'RS', flag: require('../resources/flags/rio-grande-do-sul.png') },
    Rondonia: { title: 'Rondônia', code: 'RO', flag: require('../resources/flags/rondonia.png') },
    Roraima: { title: 'Roraima', code: 'RR', flag: require('../resources/flags/roraima.png') },
    SantaCatarina: { title: 'Santa Catarina', code: 'SC', flag: require('../resources/flags/santa-catarina.png') },
    SaoPaulo: { title: 'São Paulo', code: 'SP', flag: require('../resources/flags/sao-paulo.png') },
    Sergipe: { title: 'Sergipe', code: 'SE', flag: require('../resources/flags/sergipe.png') },
    Tocantins: { title: 'Tocantins', code: 'TO', flag: require('../resources/flags/tocantins.png') },
}
